# Install wget requirement
- name: Install wget package
  yum: name=wget state=present

- name: Install KairosDB package
  yum: name=kairosdb state=present disable_gpg_check=yes

- name: Applying KairosDB configuration template
  template: src=kairosdb.properties.j2 dest=/opt/kairosdb/conf/kairosdb.properties
  notify:
    - restart kairosdb

- name: Wait for Cassandra
  wait_for:
    host: "{{ kariosdb_cassandra_rpc_address }}"
    port: "{{ kariosdb_cassandra_rpc_port }}"
  when: kairosdb_wait_for_cassandra is defined and kairosdb_wait_for_cassandra

- name: Start KairosDB service
  service: name=kairosdb state=started enabled=yes
