---
abiquo_default_properties:
  abiquo.datacenter.id: "{{ ansible_hostname }}"
  abiquo.server.api.location: "https://{{ ansible_fqdn }}/api"
  abiquo.redis.port: 6379
  abiquo.redis.host: 127.0.0.1
  abiquo.rabbitmq.addresses: "{{ abiquo_rabbitmq_addresses }}"
  abiquo.rabbitmq.password: "{{ abiquo_rabbitmq_password }}"
  abiquo.rabbitmq.username: "{{ abiquo_rabbitmq_username }}"
  abiquo.rabbitmq.virtualHost: "{{ abiquo_rabbitmq_vhost }}"
abiquo_fw_allowed_ports:
  - "8009"
  - "8010"
